# Generated by Django 5.0.6 on 2024-06-24 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('profesor', '0001_initial'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=100)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.curso')),
                ('id_inst_ed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.curso')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.profesor')),
            ],
        ),
    ]
