# Generated by Django 5.0.6 on 2024-06-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_tareas_archivo_alter_tareas_rubrica'),
        ('alumno', '0002_delete_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.curso')),
            ],
        ),
    ]
