# Generated by Django 5.0.6 on 2024-06-24 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_tareas_archivo_alter_tareas_rubrica'),
        ('alumno', '0003_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='id_tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.tareas'),
        ),
    ]
