# Generated by Django 5.0.6 on 2024-06-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_evaluacion_id_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
