# Generated by Django 5.0.6 on 2024-07-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_curso_id_inst_ed_alter_curso_id_profesor'),
        ('alumno', '0006_reclamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id_curso',
        ),
        migrations.CreateModel(
            name='alumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.curso')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_curso',
            field=models.ManyToManyField(through='alumno.alumnoCurso', to='administrador.curso'),
        ),
    ]
