# Generated by Django 5.0.6 on 2024-06-24 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=100)),
                ('id_inst_ed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.institucion')),
            ],
        ),
    ]
