# Generated by Django 5.0.6 on 2024-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='usuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
