# Generated by Django 5.0.6 on 2024-06-24 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('rubrica', models.FileField(upload_to='')),
                ('archivo', models.FileField(upload_to='')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.curso')),
            ],
        ),
    ]
