# Generated by Django 5.0.6 on 2024-06-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='archivo',
            field=models.FileField(upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='rubrica',
            field=models.FileField(upload_to='rubricas/'),
        ),
    ]
